config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home' 
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
      resources :messages, only: [ :create ]
      get :messages, to: 'messages#show'
      delete :messages, to: 'messages#destroy'
    end
  end
  get '/message', to: 'messages#index'
  #resources :messages
  #get '/messages', to: 'messages#index'
  #get '/messages/:id', to: 'messages#show'
  #post '/messages/:id', to: 'messages#create'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender,    class_name: 'User'
  belongs_to :recipient, class_name: 'User'
  validates :sender_id, presence: true
  validates :recipient_id, presence: true
  validates :content, presence: true, length: {maximum: 1000}
  default_scope -> { order(created_at: :asc) }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :logged_in_user

  def index
    @relate_users = current_user.following + current_user.followers
    if current_user.chat_with
      @chats = current_user.chat_with#.paginate(page: params[:page])
    else
      @chats = []
    end
  end

  def show
    @messages = current_user.messages_with(params[:id])
    if @messages.nil?
      @messages = []
    end
  end

  def create
    @message = Message.create(message_params)
    @messages = current_user.messages_with(params[:id])
    respond_to do |format|
      format.html { render 'show' }
      format.js
    end
  end

  def destroy
    current_user.messages_with(params[:id]).destroy_all
    redirect_to message_path
  end

  private
    def message_params
      params.require(:message).permit(:sender_id, :recipient_id, :content)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_chat.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if !current_user?(user) %>
  | <%= link_to "メッセージを送る" , messages_user_path(user) %>
  | <%= link_to "ユーザーとのメッセージを全て削除する" , messages_user_path(user), method: :delete %>
  <% end %>
</li>

app/views/messages/_message.html.erb
<li>
  <div class="row">
    <div class="<%= message.sender_id==current_user.id ? 'message-sent' : 'message-received' %>">
      <%= message.content %>
      <span class="timestamp"><%= message.created_at.strftime('%H:%M') %></span>
    </div>
  </div>
</li>

app/views/messages/create.js.erb
$("#message").append("<%= j(render 'messages/message', message: @message) %>");
$("#message_content").html("input[type=text], textarea").val("");

app/views/messages/index.html.erb
<% provide(:title, 'Messages') %>

<select onchange="window.location=this.value"  class="form-control">
  <option>フォロー中のユーザーにメッセージを送る</option>
  <% @relate_users.each do |r| %> 
    <option value="users/<%= r.id %>/messages"><%= r.name %></option>
  <% end %>
</select>

<ul class="users">
  <% @chats.each do |chat| %>
    <% #unless chat == current_user %>
      <%= render partial: "chat", locals: {user: chat} %>
    <% #end %>
  <% end %>
</ul>

app/views/messages/show.html.erb
<% provide(:title, 'Messages') %>
  <div id="message">
    <% @messages.each do |message|%>
      <%= render message %>
    <% end %>
  </div>

<!-- ajax -->
  <%= form_for(:message, remote: true) do |f| %>
    <%= f.hidden_field :sender_id,    :value => current_user.id %>
    <%= f.hidden_field :recipient_id, :value => params[:id] %>
    <%= f.text_area :content, placeholder: "新しいメッセージ..." %>
    <%= f.submit "送信", class:"btn btn-primary" %>
  <% end %>